spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/animal_welfare
    username: postgres
    password: postgres
  flyway:
    enabled: true
  docker:
    compose:
      enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html