spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/animal_welfare
    username: postgres
    password: postgres
  flyway:
    enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 25MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html