spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/animal_welfare
    username: postgres
    password: postgres
  flyway:
    enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 25MB

springdoc:
  api-docs:
    enabled: true
    path: /api-documentation/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api-documentation/swagger-ui
    supported-submit-methods:

management:
  username: default_user
  password: default_password

jwt:
  secret: f70a1a5d-240f-4b57-af03-d3390643f10f