spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/animal_welfare
    username: postgres
    password: postgres
  cloud:
    azure:
      storage:
        blob:
          account-name: devstoreaccount1
          account-key: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
          endpoint: http://localhost:10000/devstoreaccount1
          container-name: dog-images
  flyway:
    enabled: true



