name: Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin' # oder eine andere Distribution, die Java 21 unterstützt

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run Spotless Check
      run: mvn spotless:check

    - name: Run Tests
      run: mvn test

    - name: Apply Spotless
      if: failure() && contains(steps.spotless-check.outputs.result, 'spotless violation')
      run: mvn spotless:apply
